#!/bin/bash

# Nagios plugin exit codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

if [ -z "$1" -o "$2" ]; then
	echo "Usage: $0 <interface>"
	exit $STATE_UNKNOWN
fi

# Locale settings other than ISO may destroy the format by appending am/pm to
# the time

read SAR_TIME SAR_IFACE SAR_RXPCK SAR_TXPCK SAR_RXKB SAR_TXKB SAR_DISCARD <<< \
		`LC_ALL=ISO sar -n DEV | grep $1 | tail -2 | head -1`

echo "OK - $SAR_RXKB kB/s received - $SAR_TXKB kB/s sent - report from \
$SAR_TIME|rx=${SAR_RXKB}kB tx=${SAR_TXKB}kB"

exit $STATE_OK
