#!/bin/bash

# Nagios plugin exit codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

# Common commands
XPATH="xmlstarlet sel -t -v"

# Cache curl results, to reduce our hits on the API
function curl_cached() {
	CACHE_FILE=/tmp/curl_cached_`md5sum <<< "$1" | cut -d ' ' -f 1`

	if [ ! -f $CACHE_FILE ] || [ `stat -c %Y $CACHE_FILE` -lt \
			`date -d "$2 ago" +%s` ]; then
		(umask 0077; curl -s "$1" -o $CACHE_FILE)
	fi

	cat $CACHE_FILE
}

# Convert the string '1MB' to the number '1024'
function to_kb() {
	read QUANTITY UNIT <<< `echo $1 | \
			sed -n 's/^\([0-9.]*\)[ \t]*\([a-z]*\)$/\1 \L\2/ip'`
	
	case $UNIT in
		tb|t)
			bc <<< "($QUANTITY * 1024 * 1024 * 1024) / 1"
			;;
		gb|g)
			bc <<< "($QUANTITY * 1024 * 1024) / 1"
			;;
		mb|m)
			bc <<< "($QUANTITY * 1024) / 1"
			;;
		kb|k)
			bc <<< "$QUANTITY / 1"
			;;
		b|'')
			bc <<< "$QUANTITY / 1024"
			;;
		*)
			echo BAD_UNIT
			;;
	esac
}

# Convert '2456' to '2.4 MB' and '133000' to '130 MB'
function to_human() {
	if [ $1 -gt $((10 * 1024 * 1024 * 1024)) ]; then
		bc -l <<< "scale = 0; print $1 / 1024 / 1024 / 1024, \" TB\""
	elif [ $1 -gt $((1024 * 1024 * 1024)) ]; then
		bc -l <<< "scale = 1; print $1 / 1024 / 1024 / 1024, \" TB\""
	elif [ $1 -gt $((10 * 1024 * 1024)) ]; then
		bc -l <<< "scale = 0; print $1 / 1024 / 1024, \" GB\""
	elif [ $1 -gt $((1024 * 1024)) ]; then
		bc -l <<< "scale = 1; print $1 / 1024 / 1024, \" GB\""
	elif [ $1 -gt $((10 * 1024)) ]; then
		bc -l <<< "scale = 0; print $1 / 1024, \" MB\""
	elif [ $1 -gt 1024 ]; then
		bc -l <<< "scale = 1; print $1 / 1024, \" MB\""
	else
		echo $1 kB
	fi
}

# Check a response and then exit if it's bad
function check_response() {
	CODE=`$XPATH '/api/response/result/@code' <<< "$1"`
	
	if [ "$CODE" != 1000 ]; then
		echo "Bad response ($CODE): `$XPATH '/api/response/details' <<< "$1"`"
		exit $STATE_UNKNOWN
	fi
}

while getopts "k:r:w:c:" OPT; do
	case $OPT in
		k) AID=$OPTARG ;;
		r) REFERENCE=$OPTARG ;;
		w) WARN=`to_kb "$OPTARG"` ;;
		c) CRIT=`to_kb "$OPTARG"` ;;
	esac
done

if [ -z "$AID" -o -z "$REFERENCE" -o -z "$WARN" -o -z "$CRIT" ]; then
	echo "Usage: $0 -k <api key> -r <server reference> -w <warning>" \
			"-c <critical>"
	exit $STATE_UNKNOWN
fi

# Note: naming is from the perspective outside of the host, so 'in' is 'received
# from the host' and 'out' is 'sent to the host'.

API="https://secure.leaseweb.nl/api"
XPATH_SERVER_ID="/api/response/details/detail\
/server[reference = '$REFERENCE']/server_pack_id"
XPATH_TRAFFIC_IN="/api/response/details/detail\
/datatraffic/measurement/node/in"

# Fetch server id
SERVER_LIST=`curl_cached "$API/listserverpacks?aid=$AID" "1 week"`
check_response "$SERVER_LIST"
SERVER_ID=`$XPATH "$XPATH_SERVER_ID" <<< "$SERVER_LIST"`

if [ -z "$SERVER_ID" ]; then
	echo "Server reference '$REFERENCE' not found (maybe clear the cache?)"
	exit $STATE_UNKOWN
fi

# Fetch the traffic from this month and the traffic from the last 7 days
CUR_MONTH=`curl_cached "$API/network/get?aid=$AID&server_pack_id=$SERVER_ID&\
date_from=01-$(date +%m-%Y)&date_to=$(date +%d-%m-%Y)" "1 hour"`
check_response "$CUR_MONTH"
TRAF_CUR_MONTH=$(to_kb "$($XPATH "$XPATH_TRAFFIC_IN" <<< "$CUR_MONTH")")

CUR_DAYS7=`curl_cached "$API/network/get?aid=$AID&server_pack_id=$SERVER_ID&\
date_from=$(date -d '7 days ago' +%d-%m-%Y)&date_to=$(date +%d-%m-%Y)" "1 hour"`
check_response "$CUR_DAYS7"
TRAF_CUR_DAYS7=$(to_kb "$($XPATH "$XPATH_TRAFFIC_IN" <<< "$CUR_DAYS7")")

# Compute the daily traffic rate and the projected end of month traffic sum
eval `bc -l <<< "
	current = $TRAF_CUR_MONTH
	daily = $TRAF_CUR_DAYS7 / 7
	last_day = $(date -d "$(date +%Y-%m-01) + 1 month - 1 day" +%d)
	current_day = $(date +%d)
	current_hour = $(date +%H)
	hours_to_go = ((last_day - current_day) * 24) + (24 - current_hour)
	projected = current + ((daily / 24) * hours_to_go)
	scale = 0
	print \"TRAF_DAILY=\", daily / 1, \"; TRAF_PROJECTED=\", projected / 1"`

INFO="Projected traffic is `to_human $TRAF_PROJECTED` (currently at `to_human \
$TRAF_CUR_MONTH` with daily rate of `to_human $TRAF_DAILY`)"
PERF="trafficProjected=${TRAF_PROJECTED}kB;$WARN;$CRIT trafficDailyRate=\
${TRAF_DAILY}kB trafficCurrentMonth=${TRAF_CUR_MONTH}kB"

if [ $TRAF_PROJECTED -gt $CRIT ]; then
	STATE=CRITICAL;
elif [ $TRAF_PROJECTED -gt $WARN ]; then
	STATE=WARNING;
else
	STATE=OK;
fi

echo "$STATE - $INFO|$PERF"

eval exit \$STATE_$STATE

