#!/bin/bash

. lib.sh

if [ -z "$1" -o "$2" ]; then
	echo "Usage: $0 <interface>"
	exit $STATE_UNKNOWN
fi

# Locale settings other than ISO may destroy the format by appending am/pm to
# the time

read SAR_TIME SAR_IFACE SAR_RXPCK SAR_TXPCK SAR_RXKB SAR_TXKB SAR_DISCARD <<< \
		`LC_ALL=ISO sar -n DEV | grep $1 | tail -2 | head -1`

# Convert kB/s to B/s, sar reports these numbers in 1000 byte kilobytes
RX=`bc -l <<< "scale = 0; $SAR_RXKB * 1000 / 1"`
TX=`bc -l <<< "scale = 0; $SAR_TXKB * 1000 / 1"`

echo "OK - `bytes_to_human $RX`/s received - `bytes_to_human $TX`/s sent - \
report from $SAR_TIME|rx=${RX}B tx=${TX}B"

exit $STATE_OK
