#!/bin/bash

. $(dirname $0)/lib.sh

function size() {
	stat --format=%s $1 2>/dev/null
}

DOWN=
TIMEOUT=
ABERRANT=
UP=0

for URL in $@; do
	FILE=/var/lib/nagioschecks/check_urls_${URL//\//_}
	TEMP=$(mktemp)

	curl --silent --fail --max-time 30 --location --output $TEMP $URL
	CODE=$?

	if [[ $CODE = 28 ]]; then
		TIMEOUT="$TIMEOUT $URL"
	elif [[ $CODE != 0 || ! $(size $TEMP) > 0 ]]; then
		DOWN="$DOWN $URL"
	elif [[ ! -e $FILE ]]; then
		cp $TEMP $FILE
		UP=$((UP + 1))
	else
		DELTA=$((100 * $(size $TEMP) / $(size $FILE)))
		cp $TEMP $FILE

		if [[ $DELTA -lt 25 ]]; then
			ABERRANT="$ABERRANT $URL $DELTA% (${TEMP#/tmp/})"
		else
			UP=$((UP + 1))
		fi
	fi
done

INFO="$UP urls up"
STATUS=$STATE_OK

for TYPE in DOWN TIMEOUT ABERRANT; do
	if [[ ${!TYPE} ]]; then
		INFO="$INFO, ${TYPE}${!TYPE}"
		STATUS=$STATE_CRITICAL
	fi
done

echo $INFO
exit $STATUS
