#!/bin/bash

. lib.sh

if [ "$1" ]; then
	echo "Usage: $0"
	exit $STATE_UNKNOWN
fi

# Locale settings other than ISO may destroy the format by appending am/pm to
# the time
LAST_REPORT=`LC_ALL=ISO sar -b | tail -2 | head -1`
read SAR_TIME SAR_TPS SAR_RTPS SAR_WTPS SAR_BREADS SAR_BWRTNS <<< $LAST_REPORT

# Convert blocks per second to bytes per second (a block is 512 bytes)
READ=`bc -l <<< "scale = 0; $SAR_BREADS * 512 / 1"`
WRTN=`bc -l <<< "scale = 0; $SAR_BWRTNS * 512 / 1"`

echo "OK - `bytes_to_human $READ`/s read - `bytes_to_human $WRTN`/s written - \
report from $SAR_TIME|read=${READ}B wrtn=${WRTN}B"

exit $STATE_OK
