#!/bin/bash

. lib.sh

if [ -z "$1" -o "$2" ]; then
	echo "Usage: $0 <interface>"
	exit $STATE_UNKNOWN
fi

# Locale settings other than C may destroy the output format of sar by appending
# " AM" or " PM" to the time, thus causing an extra token.
LC_TIME=C

OUTPUT=`sar -n DEV | grep $1 | tail -2`

if [ `wc -l <<< "$OUTPUT"` -lt 2 ]; then
	ALT=`ls -tr1 /var/log/{sysstat,sa}/sa?? | tail -2 | head -1`
	OUTPUT=`sar -n DEV -f $ALT | grep $1 | tail -2`
fi

STATS=($OUTPUT)

# Convert kB/s to B/s, sar reports these numbers in 1000 byte kilobytes
RX=`bc -l <<< "scale = 0; ${STATS[4]} * 1000 / 1"`
TX=`bc -l <<< "scale = 0; ${STATS[5]} * 1000 / 1"`

echo "OK - `bytes_to_human $RX`/s received - `bytes_to_human $TX`/s sent - \
report from ${STATS[0]}${ALT:+ (${ALT##*/})}|rx=${RX}B tx=${TX}B"

exit $STATE_OK
