#!/usr/bin/python

import boto.ec2.cloudwatch
import sys
from datetime import datetime, timedelta

if len(sys.argv) != 4:
    print 'Usage: %s <region> <db instance id> <minimum free MB>' % sys.argv[0]
    sys.exit(1)

region = sys.argv[1]
instance = sys.argv[2]
minimum = int(sys.argv[3])
connection = boto.ec2.cloudwatch.connect_to_region(region)

if not connection:
    print 'Failed to connect to AWS'
    sys.exit(2)

stats = connection.get_metric_statistics(
    60, datetime.utcnow() - timedelta(seconds = 60), datetime.utcnow(),
    'FreeStorageSpace', 'AWS/RDS', 'Average',
    dimensions={'DBInstanceIdentifier': instance})

if not stats:
    print 'Could not find statistics'
    sys.exit(3)

free = stats[0]['Average'] / 1024 ** 2

if free < minimum:
    print 'Not enough free storage: %d MB' % free
    sys.exit(2)
else:
    print 'Free storage: %d MB' % free
    sys.exit(0)

# vim: expandtab tabstop=4
